// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGlVxqGYYUT0Nt3Py8ZlOMiPQdLD63_Mo',
    appId: '1:590231615247:web:ab9bb788fe22d6fcae707a',
    messagingSenderId: '590231615247',
    projectId: 'iti2023training',
    authDomain: 'iti2023training.firebaseapp.com',
    storageBucket: 'iti2023training.appspot.com',
    measurementId: 'G-0RQK08WP8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClRzRFDAAtapGyAx2Rb_AwOslyaN37yd8',
    appId: '1:590231615247:android:a113757bed75b8dcae707a',
    messagingSenderId: '590231615247',
    projectId: 'iti2023training',
    storageBucket: 'iti2023training.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_gUS6et1QfaXUeq3nIP1073hVAAhGWSA',
    appId: '1:590231615247:ios:3ea04f1160014564ae707a',
    messagingSenderId: '590231615247',
    projectId: 'iti2023training',
    storageBucket: 'iti2023training.appspot.com',
    iosClientId: '590231615247-r7l7ma1p6cvg0agmbchb60pkfcdmcgu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
